# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main, develop, hotfix/**, feature/register-endpoint-update ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup env vars
        run: |
          echo "tg_channel_id=-1001859011441" >> $GITHUB_ENV
          echo "tg_bot_token=6187689618:AAGY_z90QqBhqfLv4mA0SkrX0kzyZoR1drQ" >> $GITHUB_ENV
          echo "lib_version=`./library/get_version_name build.gradle`" >> $GITHUB_ENV
          echo "last_commit_author=`git log -n 1 --pretty=format:'%an'`" >> $GITHUB_ENV
          echo "last_commit_msg=`git log -n 1 --pretty=format:'%s'`" >> $GITHUB_ENV
      - name: Build and publish
        run: |
          if ./gradlew clean assembleRelease; then
            if ./gradlew publish; then
                echo "gradlew_success=true" >> $GITHUB_ENV
            else
                echo "gradlew_success=false" >> $GITHUB_ENV 
            fi
          else
            echo "gradlew_success=false" >> $GITHUB_ENV
          fi
      - name: If success -> notify in telegram
        if: ${{ env.gradlew_success == 'true' }}
        uses: appleboy/telegram-action@master
        with:
            to: ${{ env.tg_channel_id }}
            token: ${{ env.tg_bot_token }}
            format: markdown
            args: |
              ✅ Built and published Premium Helper ${{ env.lib_version }}.

              Last commit by ${{ env.last_commit_author }}: `${{ env.last_commit_msg }}`
              Action run: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
      - name: If failure -> notify in telegram
        if: ${{ env.gradlew_success == 'false' }}
        uses: appleboy/telegram-action@master
        with:
            to: ${{ env.tg_channel_id }}
            token: ${{ env.tg_bot_token }}
            format: markdown
            args: |
              ❌ Failed to build and publish Premium Helper ${{ env.lib_version }}.
              
              Last commit by ${{ env.last_commit_author }}: `${{ env.last_commit_msg }}`
              Action run: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
      - name: Exit the action with proper code
        run: |
          if [[ ${{ env.gradlew_success }} == 'false' ]]; then
            exit 1
          fi
          
          
          
